### ISSUE TITLE
Roadmap 🎯

### ISSUE THREAD

**Issue by FBruzzesi** [FBruzzesi/sklearn-smithy#3]
# Description

Tentative roadmap of additional features which would be nice to support:

- Estimator types
  - [x] [clusterer](https://github.com/FBruzzesi/sklearn-smithy/commit/3964ad316cc5d087b2a98e5ea31d0e5b02f804fc)
  - [x] [feature selector](#17)
- [ ] ~~Cross validation splitter~~ Not planned
- [x] #1
- [x] Web UI (suggested in [linkedin comment](https://www.linkedin.com/feed/update/urn:li:activity:7198240848499638274?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7198240848499638274%2C7198240973552783360%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A7198240848499638274%2C7198308094307708929%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287198240973552783360%2Curn%3Ali%3Aactivity%3A7198240848499638274%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287198308094307708929%2Curn%3Ali%3Aactivity%3A7198240848499638274%29))
   Edit: A somewhat minimal implementation in #6 
   [Streamlit WebUI](https://sklearn-smithy.streamlit.app/)
- [x] #5 
- [x] [Docs](#16)
